---
- block:
    # https://github.com/JoseExposito/touchegg/blob/master/HACKING.md#compilation
  - name: Install deps
    ansible.builtin.apt:
      name:
      - git
      - build-essential
      - gdb
      - cmake
      - debhelper
      - libudev-dev
      - libinput-dev
      - libpugixml-dev
      - libcairo2-dev
      - libx11-dev
      - libxtst-dev
      - libxrandr-dev
      - libxi-dev
      - libglib2.0-dev
      - libgtk-3-dev               # GTK is optional, see "Compilation flags"
    become: true

  - name: Git checkout source
    git:
      repo: https://github.com/JoseExposito/touchegg.git
      dest: '{{ touchegg_git_dest }}'
      update: true
      clone: true
      depth: 1

  - name: Build
    ansible.builtin.command:
        # Install to /usr so touche is happy.
        # https://github.com/JoseExposito/touche/issues/66#issuecomment-1310042350
      cmd: >
        cmake
            -DCMAKE_INSTALL_PREFIX=/usr
            -DCMAKE_BUILD_TYPE=Release
            -DAUTO_COLORS=ON
            -DUSE_SYSTEMD=ON
      chdir: '{{ touchegg_git_dest }}'
    changed_when: false

  - name: Install
    ansible.builtin.command:
      cmd: make install
      chdir: '{{ touchegg_git_dest }}'
      creates: /usr/bin/touchegg
    become: true

  - name: Clean up
    ansible.builtin.file:
      path: '{{ touchegg_git_dest }}'
      state: absent
