---
- block:

  - name: Install guake
    import_role:
      name: package
    vars:
      check_cmd: guake --version
      package_name: guake

  - name: Restore guake configuration
    shell: dconf load /apps/guake/ < {{ role_path }}/files/guake.dconf
    changed_when: false
    tags:
      - skip_in_ci    # error: Cannot spawn a message bus without a machine-id

  tags:
    - guake
