version: '3'
services:
  debian: &template
    build:
      context: .
      dockerfile: Dockerfile-debian
    volumes:
      - ../../:/source:ro
      - ../hcm_sync.sh:/hcm_sync.sh:ro
    command:
      - bash
      - /hcm_sync.sh
  arch:
    <<: *template
    build:
      context: .
      dockerfile: Dockerfile-arch
