---
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.0.11  # or specific tag
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']
