---
repos:
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2     # or specific tag
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150']

- repo: https://github.com/ansible/ansible-lint.git
  rev: v6.14.4
  hooks:
  - id: ansible-lint
    files: \.yml$
