sudo: required
services:
  - docker

before_install:
  - docker-compose -f .travis/docker/docker-compose.yml build --build-arg UID=$UID --build-arg INCLUDE_NODE_JS=true arch
  - docker-compose -f .travis/docker/docker-compose.yml build --build-arg UID=$UID --build-arg INCLUDE_NODE_JS=true debian

script:
  - .travis/run_tests.sh
