sudo: required
services:
  - docker

before_install:
  - docker-compose -f .travis/docker/docker-compose.yml build --build-arg UID=$UID arch
  - docker-compose -f .travis/docker/docker-compose.yml build --build-arg UID=$UID debian

script:
  - travis_wait 60 .travis/run_tests.sh
