- hosts: localhost

  tasks:
  - block:
    - import_role: name=skeleton
    - import_role: name=tmux
    - import_role: name=skeleton_zgen
    - import_role: name=zgen
    - import_role: name=zsh
    - import_role: name=vim
    - import_role: name=top
    - import_role: name=tig
    - import_role: name=git
    tags:
    - essentials, mini

  - block:
    - import_role: name=wget
    - import_role: name=aria2
    - import_role: name=snap
    - import_role: name=cli_tools
    - import_role: name=fzf
    tags:
    - cli

  - block:
    - import_role: name=nerd_fonts
    - import_role: name=cursor_theme
    tags:
    - gui