---
- name: Debug
  hosts: localhost
  tags:
  - always
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }} - ansible {{ ansible_version.full }}"

  - name: Package update
    action: >
      {{ ansible_pkg_mgr }} update_cache=yes
    become: true
    tags:
    - package_update

- name: Essentials
  hosts: localhost
  tags:
  - essentials
  - mini
  roles:
  - skeleton
  - tmux
  - compile_tmux
  - skeleton_zgen
  - zgen
  - zsh
  - zsh_p10k
  - vim
  - compile_vim
  - top
  - tig
  - git
  - swappiness

- name: Cli
  hosts: localhost
  tags:
  - cli
  roles:
  - wget
  - aria2
  - snap
  - cli_tools
  - fzf
  - ack
  - fzf_git
  - linuxbrew
  - smart_title
  - navi
  - navi_cheats

- name: Gui
  hosts: localhost
  tags:
  - gui
  - never
  roles:
  - nerd_fonts
  - cursor_theme
  - ime_rime
      # - guake
  - yakuake
  - gui_scripts
  - flatpak
  - obsidian
  - anki
  - fix_kde_autostart
  - kde_settings
  - wayland
  - marble_mouse

- name: Gui (skip for chrome os)
  hosts: localhost
  tags:
  - gui
  - never
  tasks:
  - block:
    - import_role: name=chrome_surfingkeys
      # - import_role: name=sxhkd
      # - import_role: name=swhkd
    - import_role: name=kdeconnect
    - import_role: name=touchegg
    when:
    - ansible_hostname != 'penguin'

- name: Dev
  hosts: localhost
  tags:
  - dev
  - never
  roles:
  - vscode
  - nvm
  - rustup
  - conda
  - 3d_printing

- name: Chrome os
  hosts: localhost
  tags:
  - chrome_os
  - never
  tasks:
  - block:
    - import_role: name=chromeos_sommelier
    when:
    - ansible_hostname == 'penguin'
