---
- block:
  - name: Install navi (via mise)
    ansible.builtin.shell:
      cmd: |
        mise use -g navi
    register: navi_install_output
    environment:
      PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
    changed_when: '"Reshimming" in navi_install_output.stderr'


  - name: Stow navi
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: navi_output
    changed_when: '"LINK" in navi_output.stderr'

  tags: navi
