---
- block:
  - name: Install the vscode flatpak
    community.general.flatpak:
      method: user
      name:  com.visualstudio.code
      state: present

  - name: stow vscode
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  tags:
  - vscode
