---
- block:
  - name: Install the vscode flatpak
    community.general.flatpak:
      method: user
      name: com.visualstudio.code
      state: present
    tags:
      - skip_in_ci

  - name: stow vscode
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Use podman-remote for dev container.
    ansible.builtin.import_tasks: dev_container.yml
    tags:
      - skip_in_ci

  tags:
    - vscode
