---
# Inspired by
# https://github.com/guoqiao/ansible-role-vim/blob/master/tasks/main.yml
- name: Check vim features
  command: bash -c "vim --version | tr '\n' ' ' | awk '/\+clipboard/&&/\+lua/'"
  register: vim_feature_check
  changed_when: false
  check_mode: false
  ignore_errors: true
  tags:
  - compile_vim
  - skip_in_ci

- block:

  - name: Install deps
    become: true
    package:
      state: latest
      name: '{{ vim_deps[ansible_pkg_mgr] }}'

  - name: Git checkout
    git:
      repo: https://github.com/vim/vim.git
      dest: '{{ vim_git_dest }}'
      update: true
      clone: true
      depth: 1

  - name: Compile vim
    shell: '{{ item }}'
    args:
      chdir: '{{ vim_git_dest }}'
    loop:
    - make distclean
    - >
      ./configure
      --prefix={{ vim_configure_prefix }}
      --with-features=huge
      --with-x
      --enable-gui=auto
      --enable-pythoninterp
      --enable-python3interp
      --with-python3-config-dir=`python3-config --configdir`
      --enable-luainterp
      --enable-rubyinterp
      --enable-largefile
    - make
    changed_when: false

  - name: Install vim
    command: make install
    args:
      chdir: '{{ vim_git_dest }}'
    become: true
    changed_when: false

  - name: Clean up
    ansible.builtin.file:
      path: '{{ vim_git_dest }}'
      state: absent

  when: vim_feature_check.rc > 0
  tags:
  - compile_vim
  - skip_in_ci
