---
- block:
  - name: Install fcitx
    package:
      name:
      - fcitx5
      - fcitx5-rime
      - '{{ rime_deployer[ansible_pkg_mgr] }}'
      - '{{ rime_wubi[ansible_pkg_mgr] }}'
    vars:
      rime_deployer:
        pacman: librime
        apt: librime-bin
      rime_wubi:
        pacman: rime-wubi
        apt: librime-data-wubi
    become: true

  - name: Stow ime_rime
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Generate rime data
    command: rime_deployer --build ~/.config/fcitx/rime /usr/share/rime-data/
    args:
      creates: ~/.config/fcitx/rime/build/wubi_pinyin.schema.yaml

  - name: Generate rime data for fcitx5
    command: rime_deployer --build ~/.local/share/fcitx5/rime /usr/share/rime-data/
    args:
      creates: ~/.local/share/fcitx5/rime/build/wubi_pinyin.schema.yaml

  tags:
  - ime_rime
