---
- block:
  - name: Install fcitx
    import_role: name=package
    vars:
      check_cmd: fcitx -v
      package_name: fcitx

  - name: install fcitx-rime
    import_role: name=package
    vars:
      check_cmd: ls /usr/share/doc/fcitx-rime/README.md
      package_name: fcitx-rime

  - name: install rime_deployer
    import_role: name=package
    vars:
      check_cmd: rime_deployer
      package_name:
        Archlinux: librime
        default: librime-bin

  - name: rime-wubi
    import_role: name=package
    vars:
      check_cmd: ls /usr/share/rime-data/wubi_pinyin.schema.yaml
      package_name:
        Archlinux: rime-wubi
        default: librime-data-wubi

  - name: stow ime_rime
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Generate rime data
    command: rime_deployer --build ~/.config/fcitx/rime /usr/share/rime-data/
    args:
      creates: ~/.config/fcitx/rime/build/wubi_pinyin.schema.yaml

  tags:
    - ime_rime
