---
- block:
  - name: Install flatpak
    package:
      name: flatpak
    become: true

  - name: Add the flathub flatpak repository remote to the user installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: user

  tags:
  - flatpak
