---
- block:

  - name: Install sxhkd
    package:
      name: sxhkd
    become: true

  - name: Stow sxhkd
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Install xinput
    package:
      name: '{{ xinput[ansible_pkg_mgr] }}'
    vars:
      xinput:
        pacman: xorg-xinput
        apt: xinput
    become: true

  tags:
  - sxhkd
