---
- block:

  - name: Install sxhkd
    import_role:
      name: package
    vars:
      check_cmd: sxhkd -v
      package_name: sxhkd

  - name: stow sxhkd
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Install xinput
    import_role:
      name: package
    vars:
      check_cmd: xinput --help
      package_name:
        Archlinux: xorg-xinput
        default: xinput

  tags:
  - sxhkd
