---
- block:
  - name: Install mise
    ansible.builtin.shell:
      cmd: |
        set -o pipefail
        curl https://mise.run | sh
      executable: /bin/bash
      creates: ~/.local/bin/mise
  - name: Stow mise
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: mise_output
    changed_when: '"LINK" in mise_output.stderr'
  - name: Install usage (required by autocomplete)
    ansible.builtin.shell:
      cmd: |
        ~/.local/bin/mise use -g usage
      executable: /bin/zsh
    changed_when: false
  - name: Mise autocomplete
    ansible.builtin.shell:
      cmd: |
        ~/.local/bin/mise completion zsh > ~/.zsh_functions/_mise
      creates: ~/.zsh_functions/_mise
  tags:
  - mise
