---
- block:
  - name: Install rust (via mise)
    ansible.builtin.shell:
      cmd: |
        mise use -g rust
    register: rustup_install_output
    changed_when: '"Reshimming" in rustup_install_output.stderr'
    environment:
      PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

  - name: Stow rustup
    ansible.builtin.command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: rustup_output
    changed_when: '"LINK" in rustup_output.stderr'

  tags:
  - rustup
