FROM alekzonder/archlinux-yaourt

RUN curl -o /etc/pacman.d/mirrorlist https://www.archlinux.org/mirrorlist/?country=US&protocol=https&ip_version=4&use_mirror_status=on \
  && sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist

# UTF-8
RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen \
  && locale-gen

USER yaourt

# for hcm
RUN yaourt --noconfirm -Syu --aur \
  coreutils \
  findutils \
  util-linux \
  grep \
  bash \
  zsh \
  ncurses \
  rsync \
  wget \
  jq \
  yq

# required tools
RUN yaourt --noconfirm -S \
  procps \
  curl \
  vim \
  tmux \
  git \
  unzip \
  zip

ENV HOME /home/timgreen
