FROM alekzonder/archlinux-yaourt

RUN curl -o /etc/pacman.d/mirrorlist https://www.archlinux.org/mirrorlist/?country=US&protocol=https&ip_version=4&use_mirror_status=on \
  && sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist

# UTF-8
RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen \
  && locale-gen

USER yaourt

# for hcm
RUN yaourt --noconfirm -Syu --aur \
  coreutils \
  findutils \
  util-linux \
  grep \
  bash \
  zsh \
  ncurses \
  rsync \
  wget \
  jq \
  python-pip \
  yq-bin

# required tools
RUN yaourt --noconfirm -Syu --aur \
  procps \
  curl \
  vim \
  tmux \
  git \
  unzip \
  zip \
  fcitx-rime

USER root
# for hcm
RUN pip install yq
ARG UID
RUN useradd -u $UID -ms /bin/bash timgreen
ENV HOME /home/timgreen
RUN mkdir /home/linuxbrew \
  && chown timgreen /home/linuxbrew
USER timgreen
