FROM debian

# for hcm
RUN apt-get update && apt-get install -y \
  coreutils \
  findutils \
  grep \
  bash \
  zsh \
  ncurses-bin \
  rsync \
  wget \
  jq \
  python-pip \
  && pip install yq

# required tools
RUN apt-get install -y \
  procps \
  curl \
  vim \
  tmux \
  git \
  unzip \
  zip \
  fcitx-rime

# UTF-8
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils locales \
  && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
  && dpkg-reconfigure --frontend=noninteractive locales \
  && update-locale LANG=en_US.UTF-8

ARG UID
RUN useradd -u $UID -ms /bin/bash timgreen
ENV HOME /home/timgreen
RUN mkdir /home/linuxbrew \
  && chown timgreen /home/linuxbrew
USER timgreen
