#!/bin/bash
ESC="\005"

u=$(sed "s/\..*$//" /proc/uptime)
printf "$ESC{= wb}"
if [ "$u" -gt 86400 ]; then
  echo "$u" | awk '{printf "%dd%dh", $1 / 86400, ($1 % 86400)/3600 }'
elif [ "$u" -gt 3600 ]; then
  echo "$u" | awk '{printf "%dh%dm", $1 / 3600, ($1 % 3600 )/60}'
elif [ "$u" -gt 60 ]; then
  echo "$u" | awk '{printf "%dm", $1 / 60 }'
else
  printf "%ds" "$u"
fi
printf "$ESC{-} "
