---
- block:
  # - name: Install fzf
  #   package:
  #     name: fzf
  #   become: true
  - name: Install fzf (via mise)
    ansible.builtin.shell:
      cmd: |
        mise use -g fzf
    register: fzf_install_output
    changed_when: '"Reshimming" in fzf_install_output.stderr'
    environment:
      PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

  - name: Stow fzf
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: fzf_output
    changed_when: '"LINK" in fzf_output.stderr'
    notify: Update zgen

  tags:
  - fzf
