---
- block:
  # - name: Install fzf
  #   package:
  #     name: fzf
  #   become: true
  - name: Install fzf (from mise)
    ansible.builtin.shell:
      cmd: |
        ~/.local/bin/mise use -g fzf
      executable: /bin/bash
    changed_when: false

  - name: Stow fzf
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: fzf_output
    changed_when: '"LINK" in fzf_output.stderr'
    notify: Update zgen

  tags:
  - fzf
