---
- block:
  - name: Stow konsole profiles
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Install yakuake & tool
    package:
      name:
      - yakuake
      - '{{ kwriteconfig5[ansible_pkg_mgr] }}'
    vars:
      kwriteconfig5:
        pacman: kconfig5
        apt: libkf5config-bin
    become: true

  - name: Restore yakuake configuration
    shell: |
      kwriteconfig5 --file ~/.config/yakuakerc --group Window --key Height 90
      kwriteconfig5 --file ~/.config/yakuakerc --group Window --key Width 100
      kwriteconfig5 --file ~/.config/yakuakerc --group Window --key DynamicTabTitles --type bool true
      kwriteconfig5 --file ~/.config/yakuakerc --group Appearance --key HideSkinBorders --type bool true
      kwriteconfig5 --file ~/.config/yakuakerc --group "Desktop Entry" --key DefaultProfile WhiteOnBlack.profile
      kwriteconfig5 --file ~/.config/konsolerc --group "Desktop Entry" --key DefaultProfile WhiteOnBlack.profile
    changed_when: false

  tags:
  - yakuake
