---
- block:
  - name: Install deno
    ansible.builtin.shell:
      cmd: >
        set -o pipefail
        curl -fsSL https://deno.land/x/install/install.sh | sh
      creates: ~/.deno/bin/deno

  - name: Stow deno
    ansible.builtin.command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Deno completions zsh
    ansible.builtin.shell:
      cmd: ~/.deno/bin/deno completions zsh > ~/.zsh_functions/_deno
      creates: ~/.zsh_functions/_deno
    tags:
    - skip_in_ci

  tags:
  - deno
