---
- block:
  - name: Install zsh
    package:
      name: zsh
    become: true

  - name: Clone zgen
    ansible.builtin.git:
      repo: https://github.com/jandamm/zgenom.git
      dest: ~/.zgenom
      update: true
      force: true

  - name: Stow zgen
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Init zgen
    command: zsh ~/sh/init_zgen.zsh
    args:
      creates: ~/.zgen/init.zsh
    failed_when: false

  tags:
  - skeleton_zgen
