sudo: required
services:
  - docker

env:
  - TEST_IMAGE=arch
  - TEST_IMAGE=debian

before_install:
  - docker-compose -f .travis/docker/docker-compose.yml build --build-arg UID=$UID $TEST_IMAGE

script:
  - .travis/run_tests.sh $TEST_IMAGE
