- name: Create local fonts directory
  file:
    path: ~/.local/share/fonts
    state: directory

- name: Download and unarchive font
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    remote_src: yes
    dest: ~/.local/share/fonts
    creates: "~/.local/share/fonts/Hack Bold Nerd Font Complete.ttf"
  register: font_download

- name: Update font cache
  command: fc-cache -rfv
  when: font_download.changed