---
- block:
  - name: Install vim
    package:
      name: vim
    become: true

  - name: Stow vim
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  - name: Vim plug install
    command: vim +PlugInstall +PlugClean! +qall
    changed_when: false
    check_mode: false

  tags:
  - vim
