---
- name: check {{ package_name }}
  command: '{{ check_cmd }}'
  register: package_check
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: install {{ package_name[ansible_distribution] | default(package_name.default) | default(package_name) }} | system
  ansible.builtin.package:
    name: '{{ package_name[ansible_distribution] | default(package_name.default) | default(package_name) }}'
    state: latest
  become: true
  when: package_check.rc > 0
