---
name: Ansible check archlinux:latest  # feel free to pick your own name

on:
  push:
  pull_request:
  schedule:
  - cron: 15 12 * * 1       # At 12:15 on Monday.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v5

    - name: ansible check with archlinux:latest
      # replace "master" with any valid ref
      uses: timgreen/check-ansible-archlinux-latest-action@master
      with:
        targets: local.yml
        tags: mini,cli,gui,dev
        skiptags: skip_in_ci,navi
